### PR TITLE
Graph structure

### PR DESCRIPTION
**Pull request by NassiHarel**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/pipeline-driver/5)

### CODE REVIEW

**Comment by yehiyam** [comment]
Reviewed 6 of 10 files at r1, 2 of 3 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

*[lib/nodes/edge.js, line 1 at r2](https://reviewable.io:443/reviews/kube-hpc/pipeline-driver/5#-L2K2cBMYinGAKeKWEVm:-L2K2cBMYinGAKeKWEVn:b-q8b3bs) ([raw file](https://github.com/kube-hpc/pipeline-driver/blob/904913ed18a817719b2503a27b9947de99d9ca0e/lib/nodes/edge.js#L1)):*
> ```JavaScript
> class Edge {
> ```

convert to function that returns an object
```js
const create = (options) => ({
    waitNode: options.isWaitNode,
    waitBatch: options.isWaitBatch,
    waitAnyBatch: options.isWaitAnyBatch
})
module.exports = create;
```

---

*[lib/nodes/nodes-map.js, line 16 at r2](https://reviewable.io:443/reviews/kube-hpc/pipeline-driver/5#-L2K9IWWvsLcbJP-zi3z:-L2K9IWXJUrQH5LtEHqm:b-orgj3r) ([raw file](https://github.com/kube-hpc/pipeline-driver/blob/904913ed18a817719b2503a27b9947de99d9ca0e/lib/nodes/nodes-map.js#L16)):*
> ```JavaScript
> class NodesMap extends EventEmitter {
> 
>     constructor(options) {
> ```

jsdocs

---

*[lib/nodes/nodes-map.js, line 16 at r2](https://reviewable.io:443/reviews/kube-hpc/pipeline-driver/5#-L2K9sVoPFyoEcF20MRs:-L2K9sVoPFyoEcF20MRt:b-7seo8t) ([raw file](https://github.com/kube-hpc/pipeline-driver/blob/904913ed18a817719b2503a27b9947de99d9ca0e/lib/nodes/nodes-map.js#L16)):*
> ```JavaScript
> class NodesMap extends EventEmitter {
> 
>     constructor(options) {
> ```

split constructor to functions

---

*[lib/nodes/nodes-map.js, line 60 at r3](https://reviewable.io:443/reviews/kube-hpc/pipeline-driver/5#-L2K_o7HxIghufxo_NPw:-L2K_o7HxIghufxo_NPx:bt4yx2o) ([raw file](https://github.com/kube-hpc/pipeline-driver/blob/a22d0a138b0486ea5d2281f6cc1cab7fc7ceb811/lib/nodes/nodes-map.js#L60)):*
> ```JavaScript
>                 })
> 
>                 inputParser.checkFlowInput(options, i);
> ```

check if checkFlowInput is in the api-server

---

*[lib/nodes/nodes-map.js, line 71 at r3](https://reviewable.io:443/reviews/kube-hpc/pipeline-driver/5#-L2KaHSInA0pBGBQdFi5:-L2KaHSInA0pBGBQdFi6:b-3jltok) ([raw file](https://github.com/kube-hpc/pipeline-driver/blob/a22d0a138b0486ea5d2281f6cc1cab7fc7ceb811/lib/nodes/nodes-map.js#L71)):*
> n => {
<details><summary><i alt="summary">Quoted 11 lines of code…</i></summary>
>             let node = this._findVirtualByTarget(n.target);
>             if (!node) {
>                 node = {
>                     id: uuidv4(),
>                     links: []
>                 }
>                 this._virtualGraph.push(node);
>             }
>             const edges = Object.entries(n.edge).filter(([k, v]) => v).map(e => { return { type: e[0] } });
>             node.links.push({ source: n.source, target: n.target, edges: edges })
>         }
</details>


extract to function

---

*[lib/nodes/nodes-map.js, line 90 at r3](https://reviewable.io:443/reviews/kube-hpc/pipeline-driver/5#-L2KcQOUE6FmlFajrrtB:-L2KcQOUE6FmlFajrrtC:b-a4hcjt) ([raw file](https://github.com/kube-hpc/pipeline-driver/blob/a22d0a138b0486ea5d2281f6cc1cab7fc7ceb811/lib/nodes/nodes-map.js#L90)):*
<details><summary><i alt="summary">Quoted 11 lines of code…</i></summary>
>     _findVirtualByTarget(target) {
>         let node = null;
>         this._virtualGraph.forEach(v => {
>             v.links.forEach(l => {
>                 if (l.target === target) {
>                     node = v;
>                 }
>             })
>         })
>         return node;
>     }
</details>


```js
this._virtualGraph.find(v=>v.links.find(l=>l.target === target));
```

---

*[lib/nodes/nodes-map.js, line 221 at r3](https://reviewable.io:443/reviews/kube-hpc/pipeline-driver/5#-L2KeLww0MEg3OGgxM_L:-L2KeLww0MEg3OGgxM_M:b-r9lorz) ([raw file](https://github.com/kube-hpc/pipeline-driver/blob/a22d0a138b0486ea5d2281f6cc1cab7fc7ceb811/lib/nodes/nodes-map.js#L221)):*
> ```JavaScript
> 
>     _removeActual(id) {
>         const index = this._actualGraph.findIndex(v => v.id === id);
> ```

create a single class of graph (actual and virtual) to encapsulate the data and the methods

---

*[lib/nodes/nodes-map.js, line 404 at r3](https://reviewable.io:443/reviews/kube-hpc/pipeline-driver/5#-L2Kh68DBcymKmwa2xwD:-L2Kh68DBcymKmwa2xwE:b1xr490) ([raw file](https://github.com/kube-hpc/pipeline-driver/blob/a22d0a138b0486ea5d2281f6cc1cab7fc7ceb811/lib/nodes/nodes-map.js#L404)):*
> ```JavaScript
>     }
> 
>     calc() {
> ```

give a real name

---

*[lib/nodes/nodes-map.js, line 420 at r3](https://reviewable.io:443/reviews/kube-hpc/pipeline-driver/5#-L2KigmTlSFlP0N9oIJW:-L2KigmU1gPvGy_5Ssvp:b-46lvbt) ([raw file](https://github.com/kube-hpc/pipeline-driver/blob/a22d0a138b0486ea5d2281f6cc1cab7fc7ceb811/lib/nodes/nodes-map.js#L420)):*
> ```JavaScript
>         const completed = succeed + failed;
>         const progress = (completed / nodes.length * 100).toFixed(2);
>         const states = Object.entries(groupedStates).map(([key, value]) => `${value.length} ${key}`);
> ```

return the raw data. not just strings
``` js
states:{
  failed:xxx
  active:yyy
}

progress


```

---

*[lib/parsers/input-parser.js, line 14 at r3](https://reviewable.io:443/reviews/kube-hpc/pipeline-driver/5#-L2KpEHG9-FC4wAx0U3B:-L2KpEHG9-FC4wAx0U3C:bhw5cfn) ([raw file](https://github.com/kube-hpc/pipeline-driver/blob/a22d0a138b0486ea5d2281f6cc1cab7fc7ceb811/lib/parsers/input-parser.js#L14)):*
> ```JavaScript
> class InputParser {
> 
>     parse(options, input, parentInput, index) {
> ```

rename to parentOutput

---

*[lib/parsers/input-parser.js, line 81 at r3](https://reviewable.io:443/reviews/kube-hpc/pipeline-driver/5#-L2KqNRfM6b0Fg74EmX0:-L2KqNRfM6b0Fg74EmX1:bbvt5q3) ([raw file](https://github.com/kube-hpc/pipeline-driver/blob/a22d0a138b0486ea5d2281f6cc1cab7fc7ceb811/lib/parsers/input-parser.js#L81)):*
> ```JavaScript
>     }
> 
>     extractObjectFromInput(input) {
> ```

rename to extractNode

---

*[lib/parsers/input-parser.js, line 285 at r3](https://reviewable.io:443/reviews/kube-hpc/pipeline-driver/5#-L2KrJybdp30wx6ExBUu:-L2KrJybdp30wx6ExBUv:b-8s2rb) ([raw file](https://github.com/kube-hpc/pipeline-driver/blob/a22d0a138b0486ea5d2281f6cc1cab7fc7ceb811/lib/parsers/input-parser.js#L285)):*
> ```JavaScript
>     }
> 
>     _tryGetPath(object, path, options, nodesInput, index) {
> ```

document for the future

---

*[lib/parsers/input-parser.js, line 300 at r3](https://reviewable.io:443/reviews/kube-hpc/pipeline-driver/5#-L2KrEoeUBdBOVP76tXZ:-L2KrEoeUBdBOVP76tX_:be8gfzi) ([raw file](https://github.com/kube-hpc/pipeline-driver/blob/a22d0a138b0486ea5d2281f6cc1cab7fc7ceb811/lib/parsers/input-parser.js#L300)):*
> ```JavaScript
>             if (options.parseParentNode) {
>                 const isWaitBatch = this._isWaitBatch(path);
>                 const type = isWaitBatch ? 'waitAnyBatch' : 'waitNode';
> ```

use consts

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kube-hpc/pipeline-driver/5)*

**Comment by yehiyam** [comment]
Reviewed 5 of 5 files at r4, 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kube-hpc/pipeline-driver/5)*

**Comment by yehiyam** [comment]
LGTM

---

Review status: all files reviewed at latest revision, 13 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kube-hpc/pipeline-driver/5#-:-L2LV428QkViZWHghFT7:bb6ywmx)*

**Comment by NassiHarel** [comment]
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

*[lib/nodes/edge.js, line 1 at r2](https://reviewable.io:443/reviews/kube-hpc/pipeline-driver/5#-L2K2cBMYinGAKeKWEVm:-L2LVkLzbZNr_xIaq6J5:b-896fix) ([raw file](https://github.com/kube-hpc/pipeline-driver/blob/904913ed18a817719b2503a27b9947de99d9ca0e/lib/nodes/edge.js#L1)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

convert to function that returns an object
```js
const create = (options) => ({
    waitNode: options.isWaitNode,
    waitBatch: options.isWaitBatch,
    waitAnyBatch: options.isWaitAnyBatch
})
module.exports = create;
```
</blockquote></details>

Done.

---

*[lib/nodes/nodes-map.js, line 16 at r2](https://reviewable.io:443/reviews/kube-hpc/pipeline-driver/5#-L2K9sVoPFyoEcF20MRs:-L2LVRdpnSD6W0zMPUvU:b-896fix) ([raw file](https://github.com/kube-hpc/pipeline-driver/blob/904913ed18a817719b2503a27b9947de99d9ca0e/lib/nodes/nodes-map.js#L16)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

split constructor to functions
</blockquote></details>

Done.

---

*[lib/nodes/nodes-map.js, line 16 at r2](https://reviewable.io:443/reviews/kube-hpc/pipeline-driver/5#-L2K9IWWvsLcbJP-zi3z:-L2LVlSHyMwPxapD9gBh:b-896fix) ([raw file](https://github.com/kube-hpc/pipeline-driver/blob/904913ed18a817719b2503a27b9947de99d9ca0e/lib/nodes/nodes-map.js#L16)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

jsdocs
</blockquote></details>

Done.

---

*[lib/nodes/nodes-map.js, line 60 at r3](https://reviewable.io:443/reviews/kube-hpc/pipeline-driver/5#-L2K_o7HxIghufxo_NPw:-L2LVTnfwLrbc1cBI5U9:b-896fix) ([raw file](https://github.com/kube-hpc/pipeline-driver/blob/a22d0a138b0486ea5d2281f6cc1cab7fc7ceb811/lib/nodes/nodes-map.js#L60)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

check if checkFlowInput is in the api-server
</blockquote></details>

Done.

---

*[lib/nodes/nodes-map.js, line 71 at r3](https://reviewable.io:443/reviews/kube-hpc/pipeline-driver/5#-L2KaHSInA0pBGBQdFi5:-L2LVUr5xkX_Q_AIQOQg:b-896fix) ([raw file](https://github.com/kube-hpc/pipeline-driver/blob/a22d0a138b0486ea5d2281f6cc1cab7fc7ceb811/lib/nodes/nodes-map.js#L71)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

> n => {
>             let node = this._findVirtualByTarget(n.target);
>             if (!node) {
>                 node = {
>                     id: uuidv4(),
>                     links: []
>                 }
>                 this._virtualGraph.push(node);
>             }
>             const edges = Object.entries(n.edge).filter(([k, v]) => v).map(e => { return { type: e[0] } });
>             node.links.push({ source: n.source, target: n.target, edges: edges })
>         }


extract to function
</blockquote></details>

Done.

---

*[lib/nodes/nodes-map.js, line 90 at r3](https://reviewable.io:443/reviews/kube-hpc/pipeline-driver/5#-L2KcQOUE6FmlFajrrtB:-L2LVWJLcmoxGscnASEZ:b-896fix) ([raw file](https://github.com/kube-hpc/pipeline-driver/blob/a22d0a138b0486ea5d2281f6cc1cab7fc7ceb811/lib/nodes/nodes-map.js#L90)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

>     _findVirtualByTarget(target) {
>         let node = null;
>         this._virtualGraph.forEach(v => {
>             v.links.forEach(l => {
>                 if (l.target === target) {
>                     node = v;
>                 }
>             })
>         })
>         return node;
>     }


```js
this._virtualGraph.find(v=>v.links.find(l=>l.target === target));
```
</blockquote></details>

Done.

---

*[lib/nodes/nodes-map.js, line 221 at r3](https://reviewable.io:443/reviews/kube-hpc/pipeline-driver/5#-L2KeLww0MEg3OGgxM_L:-L2LVX1GfV0cFDIuInMI:b-896fix) ([raw file](https://github.com/kube-hpc/pipeline-driver/blob/a22d0a138b0486ea5d2281f6cc1cab7fc7ceb811/lib/nodes/nodes-map.js#L221)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

create a single class of graph (actual and virtual) to encapsulate the data and the methods
</blockquote></details>

Done.

---

*[lib/nodes/nodes-map.js, line 404 at r3](https://reviewable.io:443/reviews/kube-hpc/pipeline-driver/5#-L2Kh68DBcymKmwa2xwD:-L2LVXj4rdJQqnJVqd1g:b-896fix) ([raw file](https://github.com/kube-hpc/pipeline-driver/blob/a22d0a138b0486ea5d2281f6cc1cab7fc7ceb811/lib/nodes/nodes-map.js#L404)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

give a real name
</blockquote></details>

Done.

---

*[lib/nodes/nodes-map.js, line 420 at r3](https://reviewable.io:443/reviews/kube-hpc/pipeline-driver/5#-L2KigmTlSFlP0N9oIJW:-L2LVZ2IykR-GGdDGNkG:b-896fix) ([raw file](https://github.com/kube-hpc/pipeline-driver/blob/a22d0a138b0486ea5d2281f6cc1cab7fc7ceb811/lib/nodes/nodes-map.js#L420)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

return the raw data. not just strings
``` js
states:{
  failed:xxx
  active:yyy
}

progress


```

</blockquote></details>

Done.

---

*[lib/parsers/input-parser.js, line 14 at r3](https://reviewable.io:443/reviews/kube-hpc/pipeline-driver/5#-L2KpEHG9-FC4wAx0U3B:-L2LVZi5dcGPuOIQzEQ6:b-896fix) ([raw file](https://github.com/kube-hpc/pipeline-driver/blob/a22d0a138b0486ea5d2281f6cc1cab7fc7ceb811/lib/parsers/input-parser.js#L14)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

rename to parentOutput
</blockquote></details>

Done.

---

*[lib/parsers/input-parser.js, line 81 at r3](https://reviewable.io:443/reviews/kube-hpc/pipeline-driver/5#-L2KqNRfM6b0Fg74EmX0:-L2LV_m0BPncAKDPtLNT:b-896fix) ([raw file](https://github.com/kube-hpc/pipeline-driver/blob/a22d0a138b0486ea5d2281f6cc1cab7fc7ceb811/lib/parsers/input-parser.js#L81)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

rename to extractNode
</blockquote></details>

Done.

---

*[lib/parsers/input-parser.js, line 285 at r3](https://reviewable.io:443/reviews/kube-hpc/pipeline-driver/5#-L2KrJybdp30wx6ExBUu:-L2LVe3fHJu0sK8YX_ZE:b-896fix) ([raw file](https://github.com/kube-hpc/pipeline-driver/blob/a22d0a138b0486ea5d2281f6cc1cab7fc7ceb811/lib/parsers/input-parser.js#L285)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

document for the future
</blockquote></details>

Done.

---

*[lib/parsers/input-parser.js, line 300 at r3](https://reviewable.io:443/reviews/kube-hpc/pipeline-driver/5#-L2KrEoeUBdBOVP76tXZ:-L2LVfAXndmXTgUaLFaz:b-896fix) ([raw file](https://github.com/kube-hpc/pipeline-driver/blob/a22d0a138b0486ea5d2281f6cc1cab7fc7ceb811/lib/parsers/input-parser.js#L300)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

use consts
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kube-hpc/pipeline-driver/5)*

**Pull request merged**
